/*

Author(s): Nick Brunet + Project Generated File
Description: Main layout styling and structure for the CPRG 306 assignments application.
Modified: 2024-09-25

*/

// By importing tailwind into this layout, all pages in the app folder will have
// access to tailwind classes.
import "./globals.css";

// Information for the HTML head element.
export const metadata = {
  title: "Web Development 2 Assignments",
  description: "Generated by create next app",
};

// Color scheme object for consistent styling across components.
export const colorScheme = {
  main: "bg-blue-200",
  secondary: "bg-blue-100",
  other: "bg-blue-50"
}

// Children will represent the page.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
