// By importing tailwind into this layout, all pages in the app folder will have
// access to tailwind classes.
import "./globals.css";

export const metadata = {
  title: "Web 2 Demo 1",
  description: "Generated by create next app",
};

// Children will represent the page.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
